apiVersion: v1
kind: Service
metadata:
  name: code-server-lb
  labels:
    app: code-server
    tier: code-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8443
  selector:
    app: code-server
    tier: code-server
